sudo: false
language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
before_install:
  -'npm install -g bower grunt-cli'
install:
  - 'bower install'
  # blacklist
after_success:
  - 'grunt build'
  
branches:
  except:
    - legacy
    - experimental

# whitelist
branches:
  only:
    - master
