sudo: false
language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
  # blacklist
branches:
  except:
    - legacy
    - experimental
    - master

# whitelist
branches:
  only:
<<<<<<< HEAD
    - master
    
=======
    - no-mini-build
    
# Webhooks notifications
>>>>>>> cb80795... Disabling mini because it breaks the build
notifications:
  webhooks:
    urls:
      - http://test1.ampath.or.ke/rebuild.php
    on_failure: never
    on_start: never
